apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: creative-rooster-nodejs-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/creative-rooster-nodejs